from utils.formatData import *
from utils.gptManager import *


async def web_query(question:str, mongoDB):
    """
        Return a short statemenet on the question asked. The context is based on the chat history that the user has.

        Args:
            question (string): the current question asked by the user
            mongoDB : mongoDB instance for reading mongoDB chat history
        Return:
            String response generated by openai
            updates the database as well
    """
    chat_history = mongoDB.read_MongoDB('chatHistory', False, None, 'web')

    if len(chat_history.get('web', [])) != 0:
        formattedChatHistory = formatChatHistory(chat_history.get('web', []))
    else:
        formattedChatHistory = []

    # Prepare the list of context to send gpt
    formatted_query = await webQuery(question, formattedChatHistory)
    return formatted_query

